### PR TITLE
added Like, Tag, Post and Comment models, Correctly this time

### PR DESCRIPTION
**Pull request by niraliG**
Added models for like, tag , post and comment! let me know if any changes to be made!

Doing this time correctly with the help of nikhil unni and Ricky, Thanks, Next time, I wont mess up

### CODE REVIEW

**Comment by nikhilunni511** [comment]
@niraliG 

1. Is this PR for only just models and the relations of these models with the user schema are apart from this PR?

2. Migration files for these models are also apart from this PR?

**Comment by niraliG** [comment]
> @niraliG
> 
> 1. Is this PR for only just models and the relations of these models with the user schema are apart from this PR?
> 2. Migration files for these models are also apart from this PR?

1. I have just defined the models, relations between them are yet to defined
2. I havent done anything for migrations files

this PR just have 4 models for Like, Tag, Comment and Post.

**Comment by nikhilunni511** [comment]
Defining relations and creating migration files also part of model creation. Now it is ok but going forward make sure that will follow this.

**Review by nikhilunni511 — APPROVED** [review]

**Comment by niraliG** [comment]
> Defining relations and creating migration files also part of model creation. Now it is ok but going forward make sure that will follow this.

okay i will keep this in mind

**Pull request merged**
